name: 'Setup protoc to env'
description: 'Download protoc compiler and add it to the PATH and PROTOC'
author: 'Arduino'
inputs:
  tagname:
    description: 'Explicit release tagname to use. Example: v3.20.2'
    default: 'v3.20.2'
  version:
    description: 'Explicit version to use. Example: 3.20.2'
    default: '3.20.2'
outputs:
  version:
    description: 'Actual version of the protoc compiler environment that has been installed'
  path:
    description: 'Path to where the protoc compiler has been installed'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'box'
  color: 'green'
